"use client";

export const dynamic = "force-dynamic";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Download, FileText, Import, Plus, Search, X } from "lucide-react";

import { SignedIn, SignedOut } from "@/auth/clerk";
import { DashboardPageLayout } from "@/components/templates/DashboardPageLayout";
import { cn } from "@/lib/utils";
import { api, type DocumentItem, type DiscoveredFile, type ExecutiveAgent } from "@/lib/executive-api";

const DOC_TYPES = ["all", "markdown", "memo", "brief", "report", "pdf", "slide"] as const;

export default function DocsPage() {
  const [docs, setDocs] = useState<DocumentItem[]>([]);
  const [agents, setAgents] = useState<ExecutiveAgent[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [showCreate, setShowCreate] = useState(false);
  const [showImport, setShowImport] = useState(false);
  const [discoveredFiles, setDiscoveredFiles] = useState<DiscoveredFile[]>([]);
  const [importing, setImporting] = useState(false);

  const handleDiscover = async () => {
    setShowImport(true);
    try {
      const files = await api.documents.discover();
      setDiscoveredFiles(files);
    } catch (e) { console.error(e); setDiscoveredFiles([]); }
  };

  const handleImport = async (file: DiscoveredFile) => {
    setImporting(true);
    try {
      const doc = await api.documents.import({ file_path: file.path, title: file.name });
      setDocs((prev) => [doc, ...prev]);
    } catch (e) { console.error(e); }
    finally { setImporting(false); }
  };

  const [batchImporting, setBatchImporting] = useState(false);
  const [batchResult, setBatchResult] = useState<{ imported: number; skipped: number } | null>(null);

  const handleBatchImport = async () => {
    setBatchImporting(true);
    try {
      const result = await api.documents.batchImport();
      setBatchResult(result);
      // Reload docs
      api.documents.list().then(setDocs).catch(console.error);
    } catch (e) { console.error(e); }
    finally { setBatchImporting(false); }
  };

  useEffect(() => {
    Promise.all([api.documents.list(), api.agents.list()])
      .then(([d, a]) => { setDocs(d); setAgents(a); })
      .catch(console.error)
      .finally(() => setLoading(false));
  }, []);

  const filtered = docs.filter((d) => {
    if (typeFilter !== "all" && d.doc_type !== typeFilter) return false;
    if (search.trim() && !d.title.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  const handleCreate = async (data: { title: string; doc_type: string; content: string; source_agent_id?: string }) => {
    try {
      const created = await api.documents.create(data);
      setDocs((prev) => [created, ...prev]);
      setShowCreate(false);
    } catch (e) { console.error(e); }
  };

  return (
    <DashboardPageLayout
      signedOut={{ message: "Sign in", forceRedirectUrl: "/home" }}
      title="Docs"
      description="Documents generated by your executive team"
      headerActions={
        <div className="flex items-center gap-2">
          <button
            onClick={handleBatchImport}
            disabled={batchImporting}
            className="flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition-fast disabled:opacity-40"
            style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}
          >
            {batchImporting ? (
              <div className="h-3.5 w-3.5 animate-spin rounded-full border border-slate-300 border-t-slate-900" />
            ) : (
              <Download className="h-3.5 w-3.5" />
            )}
            {batchImporting ? "Importing..." : "Import All"}
          </button>
          <button
            onClick={handleDiscover}
            className="flex items-center gap-1.5 rounded-lg border px-3 py-1.5 text-xs font-medium transition-fast"
            style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}
          >
            <Download className="h-3.5 w-3.5" />
            Pick
          </button>
          <button
            onClick={() => setShowCreate(!showCreate)}
            className="flex items-center gap-1.5 rounded-lg bg-[color:var(--accent)] px-3 py-1.5 text-xs font-medium text-white hover:opacity-90 transition-fast"
          >
            {showCreate ? <X className="h-3.5 w-3.5" /> : <Plus className="h-3.5 w-3.5" />}
            {showCreate ? "Cancel" : "New Doc"}
          </button>
        </div>
      }
    >
      <SignedOut>
        <div className="py-20 text-center" style={{ color: "var(--text-muted)" }}>Sign in to continue.</div>
      </SignedOut>
      <SignedIn>
        <div className="mx-auto max-w-4xl space-y-6">
          {/* Create form */}
          {/* Batch import result */}
          {batchResult && (
            <div className="rounded-xl border p-3 flex items-center gap-3" style={{ borderColor: "var(--border)", background: "var(--success-soft)" }}>
              <span className="text-sm" style={{ color: "var(--success)" }}>Imported {batchResult.imported} files, skipped {batchResult.skipped} (already imported)</span>
              <button onClick={() => setBatchResult(null)} className="ml-auto" style={{ color: "var(--text-quiet)" }}><X className="h-4 w-4" /></button>
            </div>
          )}

          {showCreate && <CreateDocForm agents={agents} onSubmit={handleCreate} />}

          {/* Import panel */}
          {showImport && (
            <div className="rounded-xl border p-5 space-y-3" style={{ borderColor: "var(--border)", background: "var(--surface)" }}>
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold" style={{ color: "var(--text)" }}>Import Local Documents</h3>
                <button onClick={() => setShowImport(false)} className="rounded p-1" style={{ color: "var(--text-muted)" }}>
                  <X className="h-4 w-4" />
                </button>
              </div>
              {discoveredFiles.length === 0 ? (
                <p className="text-xs" style={{ color: "var(--text-quiet)" }}>Scanning for documents...</p>
              ) : (
                <div className="space-y-1.5 max-h-[300px] overflow-y-auto">
                  {discoveredFiles.map((f) => (
                    <div key={f.path} className="flex items-center gap-3 rounded-lg border p-2.5" style={{ borderColor: "var(--border)" }}>
                      <FileText className="h-4 w-4 shrink-0" style={{ color: "var(--text-quiet)" }} />
                      <div className="min-w-0 flex-1">
                        <p className="text-xs font-medium truncate" style={{ color: "var(--text)" }}>{f.name}</p>
                        <p className="text-[10px] truncate" style={{ color: "var(--text-quiet)" }}>{f.path}</p>
                      </div>
                      <span className="text-[10px] shrink-0" style={{ color: "var(--text-quiet)" }}>
                        {(f.size / 1024).toFixed(0)}KB
                      </span>
                      <button
                        onClick={() => handleImport(f)}
                        disabled={importing}
                        className="rounded bg-[color:var(--accent)] px-2 py-1 text-[10px] font-medium text-white disabled:opacity-40"
                      >
                        Import
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>
          )}

          {/* Search + filter */}
          <div className="flex items-center gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2" style={{ color: "var(--text-quiet)" }} />
              <input
                className="w-full rounded-xl border py-2 pl-10 pr-4 text-sm focus:outline-none focus:ring-2 focus:ring-[color:var(--accent)]/20"
                style={{ borderColor: "var(--border)", background: "var(--surface)", color: "var(--text)" }}
                placeholder="Search docs..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <div className="flex gap-1">
              {DOC_TYPES.map((t) => (
                <button
                  key={t}
                  onClick={() => setTypeFilter(t)}
                  className={cn(
                    "rounded-full px-2.5 py-1 text-[11px] font-medium capitalize transition-fast",
                    typeFilter === t
                      ? "bg-[color:var(--accent-soft)] text-[color:var(--accent)]"
                      : "text-[color:var(--text-quiet)] hover:text-[color:var(--text-muted)]",
                  )}
                >
                  {t}
                </button>
              ))}
            </div>
          </div>

          {/* List */}
          {loading ? (
            <div className="flex items-center justify-center py-16">
              <div className="h-6 w-6 animate-spin rounded-full border-2 border-slate-300 border-t-slate-900" />
            </div>
          ) : filtered.length === 0 ? (
            <div className="rounded-xl border border-dashed p-8 text-center" style={{ borderColor: "var(--border)" }}>
              <FileText className="mx-auto h-8 w-8" style={{ color: "var(--text-quiet)" }} />
              <p className="mt-3 text-sm" style={{ color: "var(--text-muted)" }}>
                {docs.length === 0 ? "No documents yet. Create one to get started." : "No documents match your filter."}
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {filtered.map((doc) => (
                <Link
                  key={doc.id}
                  href={`/docs/${doc.id}`}
                  className="flex items-center gap-4 rounded-xl border p-4 transition-smooth hover:shadow-elevation-2"
                  style={{ borderColor: "var(--border)", background: "var(--surface)" }}
                >
                  <FileText className="h-5 w-5 shrink-0" style={{ color: "var(--text-quiet)" }} />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2">
                      <h3 className="text-sm font-medium" style={{ color: "var(--text)" }}>{doc.title}</h3>
                      <span className="rounded-full bg-[color:var(--surface-muted)] px-2 py-0.5 text-[10px] font-medium" style={{ color: "var(--text-muted)" }}>
                        {doc.doc_type}
                      </span>
                    </div>
                    {doc.agent_display_name && (
                      <p className="text-xs mt-0.5" style={{ color: "var(--text-quiet)" }}>
                        {doc.agent_avatar_emoji} {doc.agent_display_name}
                      </p>
                    )}
                  </div>
                  <span className="text-[10px] shrink-0" style={{ color: "var(--text-quiet)" }}>
                    {new Date(doc.updated_at).toLocaleDateString()}
                  </span>
                </Link>
              ))}
            </div>
          )}
        </div>
      </SignedIn>
    </DashboardPageLayout>
  );
}

function CreateDocForm({ agents, onSubmit }: {
  agents: ExecutiveAgent[];
  onSubmit: (data: { title: string; doc_type: string; content: string; source_agent_id?: string }) => void;
}) {
  const [title, setTitle] = useState("");
  const [docType, setDocType] = useState("markdown");
  const [content, setContent] = useState("");
  const [agentId, setAgentId] = useState("");

  return (
    <div className="rounded-xl border p-5 space-y-3" style={{ borderColor: "var(--border)", background: "var(--surface)" }}>
      <h3 className="text-sm font-semibold" style={{ color: "var(--text)" }}>New Document</h3>
      <input
        className="w-full rounded-lg border px-3 py-2 text-sm"
        style={{ borderColor: "var(--border)", background: "var(--surface-muted)", color: "var(--text)" }}
        placeholder="Title"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <div className="flex gap-3">
        <select className="rounded-lg border px-2 py-1.5 text-sm" style={{ borderColor: "var(--border)", color: "var(--text)" }} value={docType} onChange={(e) => setDocType(e.target.value)}>
          <option value="markdown">Markdown</option>
          <option value="memo">Memo</option>
          <option value="brief">Brief</option>
          <option value="report">Report</option>
        </select>
        <select className="rounded-lg border px-2 py-1.5 text-sm" style={{ borderColor: "var(--border)", color: "var(--text)" }} value={agentId} onChange={(e) => setAgentId(e.target.value)}>
          <option value="">No agent</option>
          {agents.map((a) => <option key={a.id} value={a.id}>{a.avatar_emoji} {a.display_name}</option>)}
        </select>
      </div>
      <textarea
        className="w-full rounded-lg border px-3 py-2 text-sm font-mono"
        style={{ borderColor: "var(--border)", background: "var(--surface-muted)", color: "var(--text)" }}
        rows={6}
        placeholder="Content (markdown)..."
        value={content}
        onChange={(e) => setContent(e.target.value)}
      />
      <button
        onClick={() => onSubmit({ title, doc_type: docType, content, ...(agentId ? { source_agent_id: agentId } : {}) })}
        disabled={!title.trim()}
        className="rounded-lg bg-[color:var(--accent)] px-4 py-2 text-sm font-medium text-white hover:opacity-90 disabled:opacity-40"
      >
        Create
      </button>
    </div>
  );
}
